{% set name = "ndtiff" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndtiff-{{ version }}.tar.gz
  sha256: 90c1759f83652c1ad330ba7d756b2fa81c9618e38c000d73717a89ce870531d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=2022.2.0
    - numpy
    - python >=3.6

test:
  imports:
    - ndtiff
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/micro-manager/NDTiffStorage
  summary: Python libraries for NDTiff datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - henrypinkard
