{% set name = "ndtiff" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndtiff-{{ version }}.tar.gz
  sha256: 2d9a7f579228caaaff8476a9498d05570848bdd46126568f49ca185aac5189fd
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=2022.2.0
    - numpy
    - python >=3.6
    - sortedcontainers

test:
  imports:
    - ndtiff
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ndtiff
  summary: Python libraries for NDTiff datasets
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/micro-manager/NDTiffStorage

extra:
  recipe-maintainers:
    - goanpeca
    - henrypinkard
